language: node_js
node_js:
  #- "4.0.0"
  - "0.12"
  - "0.11"
  - "0.10"
sudo: required
addons:
  apt:
    packages:
    - libgd2-xpm-dev
before_script:
  - npm install
  - npm run build
script:
  - npm run test