language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "4.0.0"
  - "0.12"
  - "0.11"
  - "0.10"
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libgd2-xpm-dev
before_script:
  - npm install
  - npm run build
script:
  - npm run test